base_url = "https://martalmar.eu"
title = "Mahal's blog"
compile_sass = true
default_language = "fr"

build_search_index = true

generate_feeds = false
#feed_filenames = ["https://martalmar.eu/articles"]

taxonomies = [
		   {name = "tags", rss=true }
]

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true
smart_punctuation = true
[extra]
author = "Mahal"
