base_url = "https://blog.talmar.eu"
title = "Mahal's blog"
compile_sass = true
default_language = "fr"
highlight_code = true
highlight_theme = "dracula"
build_search_index = true

generate_rss = true
feed_url = "https://blog.talmar.eu/articles"

languages = [
		  {code = "fr", rss=true, search=true},
		  {code ="en"}
]
taxonomies = [
		   {name = "tags", rss=true }
]

[extra]
author = "Mahal"
