base_url = "https://blog.talmar.eu"
title = "Mahal's blog"
compile_sass = true
default_language = "fr"

highlight_code = true
smart_punctuation = true
build_search_index = true

generate_rss = true
feed_url = "https://blog.talmar.eu/articles"

taxonomies = [
		   {name = "tags", rss=true }
]

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true
[extra]
author = "Mahal"
